global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.ApplicationModel;
global using CommunityToolkit.Maui.Storage;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using DryIoc;
global using SampleApp.Infrastructure;
global using SampleApp.ViewModels;
global using SampleApp.Views;
global using Maui.Android.InAppUpdates;
global using Maui.Biometric;
global using Microsoft.Maui.Handlers;
global using Microsoft.Maui.LifecycleEvents;
global using Polly;
global using Sharpnado.Tabs;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Reflection;
global using System.Text;
global using ZXing.Net.Maui.Controls;
global using static Microsoft.Maui.ApplicationModel.Permissions;
global using Enum = System.Enum;
global using IOPath = System.IO.Path;
global using NavigationPage = Microsoft.Maui.Controls.NavigationPage;
global using Policy = Polly.Policy;
global using PollyContext = Polly.Context;
global using WebView = Microsoft.Maui.Controls.WebView;